repos:
# Standard hooks.
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
    args: [--unsafe]  # reqd cos' gitlab yaml uses extensions

# Ensure we have good commit messages.
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.0
  hooks:
    - id: commitizen
      stages: [commit-msg]

# Standardize python formats.
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black

# Standardize sorting of imports.
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort

# Clean out results from notebooks.
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
    - id: nbstripout

# Check poetry locks is consistent.
- repo: https://github.com/python-poetry/poetry
  rev: '1.3.0'  # add version here
  hooks:
  - id: poetry-check
